default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kallario
  password: 16031973
  socket: /var/run/mysqld/mysqld.sock  

development:
  <<: *default
  database: mastertaxi_development

test:
  <<: *default
  database: mastertaxi_test

production:
  <<: *default
  database: mastertaxi_production